### ISSUE TITLE
Looker SDK does not work with Python 3.9

### ISSUE THREAD

**Issue by mcranston18** [looker-open-source/sdk-codegen#375]
I am able to run Looker SDK using Python 3.8, but not with 3.9. Steps to reproduce:

0. Ensure python 3.9 is installed
1. Create virtual env `python -m venv venv`
2. Activate virtual env `source venv/bin/activate`
3. Install looker sdk `pip install --pre looker-sdk`
4. Run the following file:
```
import looker_sdk


def run():
    sdk = looker_sdk.init31()

if __name__ == "__main__":
    run()
```
5. Witness this error:
```
(venv) ➜  looker git:(master) ✗ python -m run
Traceback (most recent call last):
  File "/Users/michaelcranston/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/michaelcranston/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/michaelcranston/src/looker/run.py", line 44, in <module>
    run()
  File "/Users/michaelcranston/src/looker/run.py", line 5, in run
    sdk = looker_sdk.init31()
AttributeError: module 'looker_sdk' has no attribute 'init31'
```

The error makes sense because when I check `looker_sdk`, I can see the `init31` method is not present.

**Comment by mcranston18** [comment]
@joeldodge79 any chance you can look at this?

**Comment by joeldodge79** [comment]
Thanks for bringing this up @mcranston18 - we have not yet [added support for 3.9](https://github.com/looker-open-source/sdk-codegen/blob/master/python/setup.py#L30) so I'll leave this open for tracking that work.

**Comment by joeldodge79** [comment]
https://pypi.org/project/looker-sdk/0.1.3b20/ should work for you
